#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# heading     : Your Settings
# description : SSH keys
# longdesc    : add public keys to allow ssh access without passwords
# navigation  : 100 600
#
# Modified (c) 2002,2006 Stephen Noble <stephen@dungog.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# uses the FormMagick Panel for remoteuseraccess 
# but pulls username from $ENV{'REMOTE_USER'};
# rather then being selected from a table
#
#----------------------------------------------------------------------

use strict;
use warnings;

use esmith::FormMagick::Panel::remoteuseraccess;

my $fm = esmith::FormMagick::Panel::remoteuseraccess->new();
$fm->display();

__DATA__
<form title="FORM_TITLE"
    header="/etc/e-smith/web/common/head.tmpl"
    footer="/etc/e-smith/web/common/foot.tmpl">
    
    <page 
        name="First"
        pre-event="print_status_message()"
        post-event="userpanel_change_settings()" >

        <description>SSHKEYS_DESCRIPTION</description>

        <field type="literal" id="User" value="get_panel_user()">
            <label>ACCOUNT</label>
        </field>

        <field type="literal" id="FullName" value="get_full_name()">
            <label>USER_NAME</label>
        </field>

        <field type="textarea"
	       rows="10" cols="30"
	       id="sshKeys"
           value="userpanel_keys_text()">
	       <label>SSH_KEYS</label>
        </field>
      
        <subroutine src="print_button('SAVE')" />
 
 
    </page>
     
</form>
